name: PFL bor create new release

on:
  workflow_dispatch:

jobs:
  execute-code:
    # runs-on: pfl-main-ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Code
        run: |
          #ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          #git status
          #git remote -v
          #git remote add upstream git@github.com:Santonclause/tempupstream.git 2>/dev/null || :
          #git status
          #git remote -v
          #git fetch upstream --tags
          release=$(curl -sL -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/Santonclause/tempupstream/releases/latest" | jq -r ".tag_name")
          echo $release



