name: PFL bor create new release

on:
  workflow_dispatch:

env:
    UPSTREAM_PROJECT: Santonclause/tempupstream
    ORIGIN_PROJECT: FastLane-Labs/temp-patch-release
    PATCH_URL: https://github.com/FastLane-Labs/sentry-patch/blob/main/announce_only.patch

jobs:
  release-new-bor-version:
    # runs-on: pfl-main-ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        
      - name: Check upstream releases
        # fetch latest releases from upstream and origin
        # compare releases and set output if there is a new release found
        # fail if releases are the same or error fetching; stop actions
        id: check-upstream-tags
        run: |
          upstream_tag=$(curl -sL -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${UPSTREAM_PROJECT}/releases/latest" | jq -r ".tag_name")
          origin_tag=$(curl -sL -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${ORIGIN_PROJECT}/releases/latest" | jq -r ".tag_name")
          echo "Upstream: $upstream_tag"
          echo "Origin: $origin_tag"
          
          echo "UPSTREAM_TAG=$upstream_tag" >> "$GITHUB_OUTPUT"
          echo "ORIGIN_TAG=$origin_tag" >> "$GITHUB_OUTPUT"
          # fail if any of the tags is null or if the tags are the same
          [[ -z $upstream_tag ]] && { echo "Got first!"; exit 1; }
          [[ -z $origin_tag ]] && { echo "Got second!"; exit 1; }
          [[ $upstream_tag == $origin_tag ]] && { echo "Got third!"; exit 1; }
          [[ -z $upstream_tag || -z $origin_tag || $upstream_tag == $origin_tag ]] && { echo "Check if tags are not null or not the same"; exit 1; }


      - name: Print tags
        if: success()
        run: |
          echo "Upstream: ${{ steps.check-upstream-tags.outputs.UPSTREAM_TAG }}
          echo "Origin: ${{ steps.check-upstream-tags.outputs.ORIGIN_TAG }}

      - name: Run Code
        run: |
          #ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git remote add upstream git@github.com:${UPSTREAM_PROJECT}.git 2>/dev/null || :
          git status
          git remote -v
          git fetch upstream --tags
          git checkout ${{ steps.check-upstream-tags.outputs.UPSTREAM_TAG }}
          curl -o pfl.patch ${PATCH_URL}
          cat pfl.patch
          rm -rf pfl.patch
          

      - name: Check version
        run: |
          echo ${{ steps.check-upstream-tags.outputs.UPSTREAM_TAG }}



